spring:
    profiles:
        active: dev
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/sample;DB_CLOSE_DELAY=-1;
        username: sa
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: com.ksolutions.config.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
        hibernate:
            ddl-auto: none
liquibase:
    dropFirst: false

server:
    port: 8080

custom:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                token-validity-in-seconds: 900
                refresh-token-validity-in-seconds: 1020

application:
